export const SET_PLAY_LIST = 'SET_PLAY_LIST';

export const SET_RECOMMEND_LIST = 'SET_RECOMMEND_LIST';

export const SET_PLAY_UI_PAGE = 'SET_PLAY_UI_PAGE';

export const SET_SONG_INFO = 'SET_SONG_INFO';

export const SET_VOLUME = 'SET_VOLUME';

export const SET_PLAY_ORDER = 'SET_PLAY_ORDER';

export const SET_SHUFFLE_LIST = 'SET_SHUFFLE_LIST';

export const SET_PLAY_STATE = 'SET_PLAY_STATE';

export const SET_CURRENT_SONG_INFO = 'SET_CURRENT_SONG_INFO';

export const SET_LOCAL_PLAY_LIST = 'SET_LOCAL_PLAY_LIST';

export const SET_NEWEST = 'SET_NEWEST';

export const SET_ALBUM_LIST = 'SET_ALBUM_LIST';